name: Create Release Artifact and Test [Python 3.6-3.9]
on:
  release:
    type: [published]

jobs:
  create-release-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build using Python 3.9
        uses: actions/setup-python@3
        with:
          python-version: 3.9
      - name: install dependencies [pip]
        run: |
          python -m pip install pip --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements_test.txt ]; then pip install -r requirements.txt; fi
          pip install -e .
      - name: run linter [flake8]
        run: flake8 .

      #- name: run unittests [pytest[
      #  run: pytest

      - name: create build artifact [sdist]
        run: python setup.py sdist

      - name: get release name
        id: get_release_name
        run: echo ::set-out name=VERSION::${GITHUB_REF/refs\/tags\}

      - name: upload build artifact
        uses: actions/upload_artifact@v3
        with:
          name: discogs-track-${{ steps.get_release_name.outputs.VERSION }}
          path: dist/*
